insert into user(id, username, password, token, email, avatar, status, registration_time, account_non_expired, account_non_locked, credentials_non_expired, enabled) values (1, 'admin', '111111', 'admin', '123@qq.com', 'https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif', 0, '2009-01-20', false, false, false, true);
insert into role(id, name, description, create_time) values (1, 'admin', '系统管理员', '2009-01-20');
insert into roles_users(user_id, role_id) values (1, 1);
insert into menu(id, path, name, icon, pid, sort) values (1, '/system', '系统管理', 'system', 0, 1);
insert into menu(id, path, name, icon, component, pid, sort) values (2, 'user', '用户管理', 'peoples', 'system/user/index', 1, 1);
insert into menu(id, path, name, icon, component, pid, sort) values (3, 'role', '角色管理', 'role', 'system/role/index', 1, 2);
insert into menu(id, path, name, icon, component, pid, sort) values (4, 'permission', '权限管理', 'permission', 'system/permission/index', 1, 3);
insert into menu(id, path, name, icon, component, pid, sort) values (5, 'menu', '菜单管理', 'menu', 'system/menu/index', 1, 4);
insert into menu(id, path, name, icon, component, pid, sort) values (6, 'resource', '资源管理', 'excel', 'system/resource/index', 1, 5);
insert into menu(id, path, name, icon, pid, sort) values (7, '/monitor', '系统运维', 'eye-open', 0, 2);
insert into menu(id, path, name, icon, component, pid, sort) values (8, 'operationLog', '操作日志', 'edit', 'monitor/operationLog/index', 7, 1);
insert into menu(id, path, name, icon, pid, sort) values (9, '/systemtool', '系统工具', 'tools', 0, 3);
insert into menu(id, path, name, icon, component, pid, sort) values (10, 'pay', '支付工具', 'alipay', 'tools/payment/index', 9, 1);
insert into menu(id, path, name, icon, component, pid, sort) values (11, 'storage', '文件存储', 'chain', 'tools/filestorage/index', 9, 2);
insert into menu(id, path, name, icon, component, pid, sort) values (12, 'message', '消息工具', 'message', 'tools/message/index', 9, 3);
insert into menu(id, path, name, icon, component, pid, sort) values (13, 'rabbitMQ', 'rabbitMQ配置', 'codeConsole', 'tools/rabbitMQ/index', 9, 4);
insert into roles_menus(menu_id, role_id) values (1, 1);
insert into roles_menus(menu_id, role_id) values (2, 1);
insert into roles_menus(menu_id, role_id) values (3, 1);
insert into roles_menus(menu_id, role_id) values (4, 1);
insert into roles_menus(menu_id, role_id) values (5, 1);
insert into roles_menus(menu_id, role_id) values (6, 1);
insert into roles_menus(menu_id, role_id) values (7, 1);
insert into roles_menus(menu_id, role_id) values (8, 1);
insert into roles_menus(menu_id, role_id) values (9, 1);
insert into roles_menus(menu_id, role_id) values (10, 1);
insert into roles_menus(menu_id, role_id) values (11, 1);
insert into roles_menus(menu_id, role_id) values (12, 1);
insert into roles_menus(menu_id, role_id) values (13, 1);
insert into permission(id, name, alias, create_time, pid) values (1, 'ADMIN', '超级管理员', '2009-01-20', 0);
insert into roles_permissions(role_id, permission_id) values (1, 1);